### ISSUE TITLE
Update for the upcoming IPL season

### ISSUE THREAD

**Issue by saifshaikh1805** [crazynayan/ipl2020#5]
Hey, great work! Can you update this for the upcoming IPL season. I want to use it but I'm a JavaScript developer, not a python developer.

**Comment by crazynayan** [comment]
No plans for developing it for ipl2022. I had done it for ipl2021. The link is [ipl2021](https://github.com/Crazy-Ideas/ipl2021)

**Comment by saifshaikh1805** [comment]
I am building it myself using React JS. Can you please be a part of it? I could use your experience.

**Comment by crazynayan** [comment]
Sure, share me the link and I can join
